import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'docs',
    },
  ],
  examplesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'examples',
    },
  ],
}

export default sidebars
