name: Deploy and Publish

on:
  push:
    branches:
      - main

jobs:
  publish-eeaas:
    name: Publish to npm
    needs: deploy-eeaas-demo
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write # needed for provenance data generation

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup environment
        uses: actions/setup-node@v5
        with:
          node-version: '22.19.0'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Configure Git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Create release
        run: npx nx release --skip-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish packages
        run: npx nx release publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

  deploy-eeaas-demo:
    name: Deploy demo site
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: actions/setup-node@v5
        with:
          node-version: '22.19.0'

      - name: Install dependencies
        run: npm install

      - name: Configure Git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Deploy to GitHub pages
        run: npx nx deploy docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
